### ISSUE TITLE
Automate version submittion thanks to Kodi addon submitter

### ISSUE THREAD

**Issue by thomas-ernest** [Catch-up-TV-and-More/resource.images.catchuptvandmore#41]
It is possible to use https://github.com/xbmc/kodi-addon-submitter in GitHub workflow in order to submit PR to official Kodi repository.
I plugged it in my addon for exampel : https://github.com/thomas-ernest/plugin.video.arteplussept/blob/master/.github/workflows/release-addon.yml#L10-L18
I also see this example : https://github.com/romanvm/kodi.tvmaze/blob/master/.github/workflows/publish-addon.yml#L35
There is a need to create a GitHub token (with a validity period) and set it as a secret in the current repo.

**Comment by joaopa00** [comment]
Ummm I do not understand what you mean. I have a personal token for all my github repos (personal and CUTVM)
But I do not understand how to create one for CUTVM repo

**Comment by thomas-ernest** [comment]
Sorry I made a shortcut.
You need a token (rather the one for CUTVM) only with access to public repo. No other permission needed.
The token value needs to be saved in a Secret attached to the repository with the action submitting the new addon version.

The GitHub action kodi submitter use this secret containing the token to auth and create the PR in kodi repo via GitHub API.

**Comment by thomas-ernest** [comment]
Great ! I will try with this secret soon and keep you posted.

**Comment by thomas-ernest** [comment]
Please note I also add to create a secret EMAIL to make the job work.
More details in PR.

**Comment by thomas-ernest** [comment]
Hello @joaopa00,

Thank you for merging the PR, but the build fail, because secret EMAIL is missing.

See error message in logs https://github.com/Catch-up-TV-and-More/resource.images.catchuptvandmore/actions/runs/6541261959/job/17762519552 : 
```
Traceback (most recent call last):
  File "/usr/local/bin/submit-addon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/addon_submitter/__main__.py", line 70, in main
    bool(gh_username), bool(gh_token), bool(user_email)
addon_submitter.utils.AddonSubmissionError: GitHub username, token and user email must be specified either via environment variables or as command line arguments.
Provided parameters:
GitHub username: True, GitHub token: True, user email: False
```

**Comment by joaopa00** [comment]
I think I have done. I will close this issue when we release a new version and if the bug is fixed.
